### ISSUE TITLE
ModuleNotFoundError: No module named 'neumai_tools'

### ISSUE THREAD

**Issue by s348268281** [NeumTry/NeumAI#30]
python----3.10.12
neumai----0.0.33

error:
Traceback (most recent call last):
  File "/Users/xxxxxx/xxxxxx/neum_test.py", line 4, in <module>
    from neumai.Chunkers.RecursiveChunker import RecursiveChunker
  File "/Users/xxxxxx/miniforge3/lib/python3.10/site-packages/neumai/Chunkers/__init__.py", line 3, in <module>
    from .CustomChunker import CustomChunker
  File "/Users/xxxxxx/miniforge3/lib/python3.10/site-packages/neumai/Chunkers/CustomChunker.py", line 4, in <module>
    from neumai_tools.SemanticHelpers import semantic_chunking
ModuleNotFoundError: No module named 'neumai_tools'

**Comment by ddematheu** [comment]
Thanks for reporting this bug. Fix will be added in version 0.0.34 which is going out shortly.

**Comment by ddematheu** [comment]
As a short term unblock, pip install neumai-tools

This requirement will be removed in the next version.

**Comment by ddematheu** [comment]
Fix pushed in release 0.0.34.
